spring.application.name=tajappointments

spring.datasource.url=postgresql://postgres:[YOUR-PASSWORD]@db.vmonbkoyuhkcbwxmypqn.supabase.co:5432/postgres
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver